name: MoodyFishing
version: '${project.version}'
main: com.toonystank.moodyfishing.MoodyFishing
api-version: '1.20.1'
depend: [ WorldEdit, WorldGuard ]
dependencies:
  server:
    WorldGuard:
      load: AFTER
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: AFTER
      required: true
      join-classpath: true

